provider: ollama
model: deepseek-coder:6.7b
base_url: http://localhost:11434
params:
  temperature: 0.1

input_path: ../data
input_glob: "*.jsonl"
field: code
output_path: ./outputs
instruction: ./prompts/refactor_python.j2
template_vars:
  language: python
  goal: improve readability and remove dead code

concurrency: 4
retry: 3
cache_dir: .cache
resume: true
strip_fences: true
auto_extract_code: true
